---
abstract: 'Check your Bank Mandiri accounts from Perl'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Slurp: 0
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-Bank-ID-Mandiri
requires:
  App::Options: 0
  DateTime: 0
  File::HomeDir: 0
  Finance::Bank::ID::Base: 0.22
  HTTP::Headers::Patch::DontUseStorable: 0
  LWP::Protocol::Net::Curl: 0.007
  Log::Any: 0
  Log::Any::App: 0.23
  Moo: 0
  YAML: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Finance-Bank-ID-Mandiri/
  repository: http://github.com/sharyanto/perl-Finance-Bank-ID-Mandiri
version: 0.24
